### ISSUE TITLE
Esri Basemaps cannot be faded

### ISSUE THREAD

**Issue by SarahLechler** [conterra/mapapps-basemap-fader#2]
Esri Basemaps  structure changed so they cannot be loaded as layer consequently cannot be faded

**Comment by sholtkamp** [comment]
Fixed in [commit 7a67304b1d18bd032ba0ec2ac24e0eaa7ae3b1eb](https://github.com/conterra/mapapps-basemap-fader/commit/7a67304b1d18bd032ba0ec2ac24e0eaa7ae3b1eb) by loading Esri basemaps as AGS_TILED basemaps.
